In [36]:
import pandas as pd

In [243]:
movie = pd.read_csv('movies.csv')

In [244]:
movie

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [122]:
movie['title'].iloc[0]

'Toy Story (1995)'

In [263]:
tags = pd.read_csv('tags.csv')

In [264]:
tags

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

In [265]:
tags_2 = (tags.groupby('movieId')['tag'].agg("|".join).reset_index())

In [266]:
type(tags_2)

pandas.core.frame.DataFrame

In [267]:
tags_2

      movieId                                              tag
0           1                                  pixar|pixar|fun
1           2     fantasy|magic board game|Robin Williams|game
2           3                                        moldy|old
3           5                                 pregnancy|remake
4           7                                           remake
...       ...                                              ...
1567   183611                      Comedy|funny|Rachel McAdams
1568   184471  adventure|Alicia Vikander|video game adaptation
1569   187593                Josh Brolin|Ryan Reynolds|sarcasm
1570   187595                          Emilia Clarke|star wars
1571   193565                    anime|comedy|gintama|remaster

[1572 rows x 2 columns]

In [268]:
data = movie.merge(tags_2,on='movieId',how='left')

In [269]:
print(data['title'].iloc[0])

Toy Story (1995)

In [270]:
data.sample(10)

,movieId,title,genres,tag
383,440,Dave (1993),Comedy|Romance,President
9142,147326,The Adventures of Sherlock Holmes and Doctor W...,Crime|Mystery,NaN
2611,3496,Madame Sousatzka (1988),Drama,NaN
9163,148632,Applesauce (2015),Comedy,NaN
8064,99117,This Is 40 (2012),Drama,NaN
8582,117133,Painted Skin (2008),Action|Drama|Thriller,NaN
6279,47644,Invincible (2006),Drama,NaN
1804,2404,Rambo III (1988),Action|Adventure|Thriller|War,NaN
5733,30745,Gozu (Gokudô kyôfu dai-gekijô: Gozu) (2003),Comedy|Crime|Drama|Horror|Mystery,NaN
6682,58047,"Definitely, Maybe (2008)",Comedy|Drama|Romance,Rachel Weisz|Ryan Reynolds

In [223]:
data.describe()

             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [271]:
data['genres'] = data['genres'].str.split('|')
data['tag'] = data['tag'].str.split('|')

In [272]:
data

,movieId,title,genres,tag
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",NaN
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]"
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",NaN
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",NaN
9739,193585,Flint (2017),[Drama],NaN
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",NaN
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],NaN

In [235]:
print(data['title'].iloc[0])

Toy Story (1995)

In [273]:
data['clean_title'] =data['title'].str.replace(r'\s*\(\d{4}\)$', '', regex=True)

toy story 1995

In [280]:
data

,movieId,title,genres,tag,clean_title
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",NaN,Waiting to Exhale
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II
...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",NaN,Black Butler: Book of the Atlantic
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",NaN,No Game No Life: Zero
9739,193585,Flint (2017),[Drama],NaN,Flint
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",NaN,Bungo Stray Dogs: Dead Apple
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],NaN,Andrew Dice Clay: Dice Rules

In [281]:
data['tag'] = data['tag'].apply(lambda x: x if isinstance(x, list) else [])

In [282]:
data

,movieId,title,genres,tag,clean_title
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II
...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero
9739,193585,Flint (2017),[Drama],[],Flint
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules

In [283]:
data['tags'] = data['genres'] + data['tag']

In [284]:
data.head()

,movieId,title,genres,tag,clean_title,tags
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,"[Adventure, Animation, Children, Comedy, Fanta..."
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,"[Adventure, Children, Fantasy, fantasy, magic ..."
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,"[Comedy, Romance, moldy, old]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,"[Comedy, pregnancy, remake]"

In [285]:
data['tags'] = data['tags'].apply(lambda x:" ".join(x))

In [286]:
data.head()

,movieId,title,genres,tag,clean_title,tags
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake

# Task 2

In [287]:
data['clean_text']=data['tags'].str.lower()

In [288]:
data

,movieId,title,genres,tag,clean_title,tags,clean_text
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),[Drama],[],Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules,Comedy,comedy

In [57]:
import re

In [58]:
def remove_punctuation(text):
    return re.sub(r'[^\w\s]','',text)

In [289]:
data['clean_text'] = data['clean_text'].apply(remove_punctuation)

In [291]:
data

,movieId,title,genres,tag,clean_title,tags,clean_text
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),[Drama],[],Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules,Comedy,comedy

In [62]:
def remove_spl_char(text):
    return re.sub(r'[^a-zA-Z0-9\s]','',text)

In [292]:
data['clean_text'] = data['clean_text'].apply(remove_spl_char)

In [293]:
data

,movieId,title,genres,tag,clean_title,tags,clean_text
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),[Drama],[],Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules,Comedy,comedy

In [66]:
pip install nltk

Requirement already satisfied: nltk in C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.9.4)
Requirement already satisfied: click in C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (4.68.2)
Requirement already satisfied: colorama in C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [294]:
from nltk.corpus import stopwords

In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [295]:

stop_words = set(stopwords.words('english'))

In [296]:
li=[]
def remove_stopwords(text):
    for i in text.split():
        if i not in stop_words:
            li.append(i)
    x = li[:]  
    li.clear()      
    return " ".join(x)

In [31]:
remove_stopwords('hello the name of me a shree')

'hello name shree'

In [297]:
data['clean_text'] = data['clean_text'].apply(remove_stopwords)

In [299]:
data

,movieId,title,genres,tag,clean_title,tags,clean_text
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),[Drama],[],Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules,Comedy,comedy

In [300]:
data.isnull().sum()

movieId        0
title          0
genres         0
tag            0
clean_title    0
tags           0
clean_text     0
dtype: int64

In [301]:
data.dropna()

,movieId,title,genres,tag,clean_title,tags,clean_text
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),[Drama],[],Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules,Comedy,comedy

In [302]:
data.dropna(axis=1)

,movieId,title,genres,tag,clean_title,tags,clean_text
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]","[pixar, pixar, fun]",Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]","[fantasy, magic board game, Robin Williams, game]",Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),"[Comedy, Romance]","[moldy, old]",Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",[],Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),[Comedy],"[pregnancy, remake]",Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),"[Action, Animation, Comedy, Fantasy]",[],Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),"[Animation, Comedy, Fantasy]",[],No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),[Drama],[],Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),"[Action, Animation]",[],Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),[Comedy],[],Andrew Dice Clay: Dice Rules,Comedy,comedy

In [303]:
data.drop(columns=['genres','tag'])

,movieId,title,clean_title,tags,clean_text
0,1,Toy Story (1995),Toy Story,Adventure Animation Children Comedy Fantasy pi...,adventure animation children comedy fantasy pi...
1,2,Jumanji (1995),Jumanji,Adventure Children Fantasy fantasy magic board...,adventure children fantasy fantasy magic board...
2,3,Grumpier Old Men (1995),Grumpier Old Men,Comedy Romance moldy old,comedy romance moldy old
3,4,Waiting to Exhale (1995),Waiting to Exhale,Comedy Drama Romance,comedy drama romance
4,5,Father of the Bride Part II (1995),Father of the Bride Part II,Comedy pregnancy remake,comedy pregnancy remake
...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,action animation comedy fantasy
9738,193583,No Game No Life: Zero (2017),No Game No Life: Zero,Animation Comedy Fantasy,animation comedy fantasy
9739,193585,Flint (2017),Flint,Drama,drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Bungo Stray Dogs: Dead Apple,Action Animation,action animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Andrew Dice Clay: Dice Rules,Comedy,comedy

In [351]:
import pickle
with open("movie_list.pickle","wb") as movies:
    pickle.dump(data,movies)

# Task 3

In [304]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1,2))

tfidf_matrix = tfidf.fit_transform(data['tags'])

tfidf_matrix.shape

(9742, 5000)

# Task 4

In [305]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

In [306]:
similarity_matrix.shape

(9742, 9742)

In [348]:
import numpy as np
similarity = similarity_matrix.astype(np.float32)

In [350]:
import joblib
joblib.dump(similarity,"similarity.joblib",compress=('gzip',9))

['similarity.joblib']

In [310]:
similarity_df = pd.DataFrame(similarity_matrix)

In [311]:
similarity_df.head()

,0,1,2,3,4,5,6,7,8,9,...,9732,9733,9734,9735,9736,9737,9738,9739,9740,9741
0,1.000000,0.048399,0.006967,0.022132,0.007886,0.0,0.010298,0.117013,0.0,0.037990,...,0.030614,0.067354,0.032053,0.135962,0.0,0.169868,0.209193,0.000000,0.067904,0.070419
1,0.048399,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.197704,0.0,0.029657,...,0.000000,0.000000,0.000000,0.000000,0.0,0.062520,0.076993,0.000000,0.000000,0.000000
2,0.006967,0.000000,1.000000,0.095418,0.011080,0.0,0.108985,0.000000,0.0,0.000000,...,0.015018,0.000000,0.045033,0.000000,0.0,0.017240,0.021231,0.000000,0.000000,0.098935
3,0.022132,0.000000,0.095418,1.000000,0.035198,0.0,0.141042,0.000000,0.0,0.000000,...,0.047710,0.068876,0.690492,0.000000,0.0,0.054768,0.067446,0.290466,0.000000,0.314295
4,0.007886,0.000000,0.011080,0.035198,1.000000,0.0,0.271356,0.000000,0.0,0.000000,...,0.017000,0.000000,0.050976,0.000000,0.0,0.019515,0.024033,0.000000,0.000000,0.111992

Explain briefly why cosine similarity is used?
Cosine similarity measures how similar the direction of two vectors are. It measures the angle between two vectors. It focuses on similarity of word distibution rather than document length and make effective for textual content. Mostly used in recommendation system.

# Task 5

In [167]:
similarity_matrix[index]

array([0.        , 0.        , 0.        , ..., 0.80903177, 1.        ,
       0.5669356 ], shape=(1572,))

In [175]:
sorted(enumerate(recommend('tomb raider')),reverse=True,key=lambda x:x[1])[1:6]

[(65, np.float64(1.0)),
 (81, np.float64(1.0)),
 (143, np.float64(1.0)),
 (288, np.float64(1.0)),
 (290, np.float64(1.0))]

In [4]:
similarity_matrix[0]

array([1.        , 0.04839902, 0.0069669 , ..., 0.        , 0.06790353,
       0.07041881], shape=(9742,), dtype=float32)

In [341]:
def recommend(item_name,top_n =5):
    #find index of selected item
    item_index = data[data['clean_title']==item_name].index[0]

    #compute similarity score
    recomedation = similarity_matrix[item_index]

    #sort
    list = sorted(enumerate(recomedation),reverse=True,key=lambda x:x[1])
    top_movies = list[1:top_n+1]

    for idx, score in top_movies:
        print(data.iloc[idx]['title'])

In [346]:
recommend('Safe')

Safe (1995)
Hideaway (1995)
Red Rock West (1992)
Blink (1994)
Malice (1993)

In [343]:
recommend('Roommates')

Big Bully (1996)
Antonia's Line (Antonia) (1995)
Nobody Loves Me (Keiner liebt mich) (1994)
Blue in the Face (1995)
Jeffrey (1995)

In [344]:
recommend('Ghost')

Michael (1996)
Defending Your Life (1991)
Price of Milk, The (2000)
Alice (1990)
Juliet of the Spirits (Giulietta degli spiriti) (1965)

# Task 6

In [7]:
import streamlit as st
import joblib
import pickle

similarity_matrix = joblib.load("similarity.joblib","rb")

similarity_matrix[0]

C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\contextlib.py:141: UserWarning: mmap_mode "rb" is not compatible with compressed file similarity.joblib. "rb" flag will be ignored.
  return next(self.gen)

array([1.        , 0.04839902, 0.0069669 , ..., 0.        , 0.06790353,
       0.07041881], shape=(9742,), dtype=float32)

In [ ]:
similarity_matrix = joblib.load("similarity.joblib","rb")

with open("movie_list.pickle","rb") as m:
    movies = pickle.load(m)


movies = movies['clean_title'].values

def recommend(m_name,top_n =5):
    #find index of selected item
    item_index = movies[movies['clean_title']==m_name].index[0]

    #compute similarity score
    recomedation = similarity_matrix[item_index]

    #sort
    list = sorted(enumerate(recomedation),reverse=True,key=lambda x:x[1])
    top_movies = list[1:top_n+1]

    recommend_list = []
    for idx, score in top_movies:
        recommend_list.append(movies.iloc[idx]['title'])
    return recommend_list


r=recommend('Heat')
for i in r:
    print(i)

C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\contextlib.py:141: UserWarning: mmap_mode "rb" is not compatible with compressed file similarity.joblib. "rb" flag will be ignored.
  return next(self.gen)

array(['Toy Story', 'Jumanji', 'Grumpier Old Men', ..., 'Flint',
       'Bungo Stray Dogs: Dead Apple', 'Andrew Dice Clay: Dice Rules'],
      shape=(9742,), dtype=object)